### ISSUE TITLE
GituHub Service fails if used more than once per deployment

### ISSUE THREAD

**Issue by ALRubinger** [redhat-kontinuity/catapult#96]
Observed while manually deploying the application into WildFly and executing requests from the browser to the `CatapultResource`:

`http://127.0.0.1:8080/kontinuity-catapult/api/catapult/fling?source_repo=jboss-developer/jboss-eap-quickstarts`

On client side (browser):

```
Context Path:
/kontinuity-catapult

Servlet Path:
/api

Path Info:
/catapult/fling

Query String:
source_repo=jboss-developer/jboss-eap-quickstarts

Stack Trace
org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Could not create GitHub client
...
```

On server logs:
```
Caused by: java.io.FileNotFoundException: https://api.github.com/user
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
	at org.kohsuke.github.Requester.parse(Requester.java:483)
	at org.kohsuke.github.Requester._to(Requester.java:236)
	at org.kohsuke.github.Requester.to(Requester.java:203)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:276)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:143)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:196)
	at org.kontinuity.catapult.service.github.impl.kohsuke.GitHubServiceFactoryImpl.create(GitHubServiceFactoryImpl.java:59)
	... 65 more
```

**Comment by ALRubinger** [comment]
Note: this is currently present on ALRubinger/55 branch.

**Comment by ALRubinger** [comment]
No longer observed and #55 is now upstream
